#!/usr/bin/env python

import argparse
import sys
import json

class Cell:
  def __init__(self, dict):
    self.x = int(dict['x'])
    self.y = int(dict['y'])

  def __str__(self):
    return "(" + str(self.x) + ", " + str(self.y) + ")"

class Unit:
  def __init__(self, dict):
    self.members = [Cell(member) for member in dict['members']]
    self.pivot   = Cell(dict['pivot'])

class Input:
  def __init__(self, dict):
    self.id           = int(dict['id'])
    self.units        = [Unit(unit) for unit in dict['units']]
    self.width        = int(dict['width'])
    self.height       = int(dict['height'])
    self.filled       = [Cell(cell) for cell in dict['filled']]
    self.sourceLength = int(dict['sourceLength'])
    self.sourceSeeds  = [int(seed) for seed in dict['sourceSeeds']]

def output(problemId, seed, tag, solution):
  return { "problemId": problemId, "seed": seed, "tag": tag, "solution": solution }

def solve(height):
  return '45' * (height / 2)

parser = argparse.ArgumentParser()
parser.add_argument('-f', help='Input json file.')
parser.add_argument('-t', help='Ignored.')
parser.add_argument('-m', help='Ignored.')
parser.add_argument('-c', help='Ignored.')
parser.add_argument('-p', help='Ignored.')

with open(parser.parse_args().f) as fp:
  input = Input(json.load(fp))
  print json.dumps([output(input.id, seed, "jancode", solve(input.height))
                    for seed in input.sourceSeeds])
